flags: 
  resyn:
    resyn: true
packages:
  - '.'
resolver: lts-15.3
extra-deps:
  - git: https://github.com/dcao/haskell-z3
    commit: a0661c19e33180931dfd2111477931792a5ef2dc
#  - limp-0.3.2.3
#  - limp-cbc-0.3.2.3
nix:
  packages: [zlib.dev, zlib.out, pkgconfig, z3]
# extra-include-dirs:
#  - <z3-home>/src/api
# extra-lib-dirs:
#  - <z3-home>/build  
